### ISSUE TITLE
登录密码

### ISSUE THREAD

**Issue by MicrophoneBen** [rutkowskij/vaadin-boot-bootstrap#1]
请问项目登录的用户名密码分别是什么

**Comment by rutkowskij** [comment]
there are two users initialized on application startup:
https://github.com/rutkowskij/vaadin-boot-bootstrap/blob/f7dd4c508573a106bc8917eda7f83057d38dff05/src/main/java/io/thingcare/bootstrap/BootstrapApplication.java#L34

admin@thingcare.io
user@thingcare.io

both with '1234' password
